rough draft
cloudyr/aws.ec2metadata pull request #11
Opened 2022-06-15 16:41 UTC by condour

Please ensure the following before submitting a PR:

 - [ ] if suggesting code changes or improvements, [open an issue](https://github.com/cloudyr/aws.ec2metadata/issues/new) first
 - [ ] for all but trivial changes (e.g., typo fixes), add your name to [DESCRIPTION](https://github.com/cloudyr/aws.ec2metadata/blob/master/DESCRIPTION)
 - [ ] for all but trivial changes (e.g., typo fixes), documentation your change in [NEWS.md](https://github.com/cloudyr/aws.ec2metadata/blob/master/NEWS.md) with a parenthetical reference to the issue number being addressed
 - [ ] if changing documentation, edit files in `/R` not `/man` and run `devtools::document()` to update documentation
 - [ ] add code or new test files to [`/tests`](https://github.com/cloudyr/aws.ec2metadata/tree/master/tests/testthat) for any new functionality or bug fix
 - [ ] make sure `R CMD check` runs without error before submitting the PR

2023-04-17 18:45 UTC, laurenkahn requested changes
Test 1: EC2 using IMDSv1, Sys.setenv(USE_IMDS_TOKEN="TRUE")
Expected result: Should be able to access S3.
Actual result: Success, able to access S3.

Test 2: EC2 using IMDSv1, Sys.setenv(USE_IMDS_TOKEN="FALSE") or not set at all.
Expected result: Should be able to access S3, as in the original code.
Actual result: Failure - see comment. Header cannot be NULL.

Test 3: EC2 using IMDSv2, Sys.setenv(USE_IMDS_TOKEN="TRUE")
Expected result: Should be able to access S3 (unlike before).
Actual result: Success, able to access S3.

Test 4: EC2 using IMDSv2, Sys.setenv(USE_IMDS_TOKEN="FALSE") or not set at all.
Expected result: Should not be able to access S3, as in the original code.
Actual result: Not able to access S3, but for wrong reason (header = NULL). Addressing test #2's failure will fix this.

2023-04-17 18:45 UTC, laurenkahn commented on R/aws.ec2metadata-package.R
> +    curl::handle_setheaders(handle, 'X-aws-ec2-metadata-token' = token)
This fails if token = NULL. For example if I use an EC2 using IMDSv1, and I don't set `USE_IMDS_TOKEN` to TRUE, and I run `aws.ec2metadata::metadata$iam_role_names()` I get the following error:

Error in curl::handle_setheaders(handle, `X-aws-ec2-metadata-token` = token): All headers must be strings.

Using a blank string instead seems to work when a token isn't required (IMDSv1).

2023-04-18 21:37 UTC, condour commented on R/aws.ec2metadata-package.R
> +    curl::handle_setheaders(handle, 'X-aws-ec2-metadata-token' = token)
I've added a check for is.null prior to setting the header. I'm unable to test at the moment, so I would appreciate if you can verify that it solves the issue. Thanks!

2023-05-02 23:31 UTC, laurenkahn commented on R/aws.ec2metadata-package.R
> +    curl::handle_setheaders(handle, 'X-aws-ec2-metadata-token' = token)
This works! The tests described above all have the expected results now.

2023-05-02 23:31 UTC, laurenkahn approved these changes

2023-05-03 21:53 UTC, condour commented on R/aws.ec2metadata-package.R
> +    curl::handle_setheaders(handle, 'X-aws-ec2-metadata-token' = token)
Thanks! Now I guess we just need someone to merge?

2024-02-01 15:38 UTC, daltschu22 commented
Is there a reason this hasnt been merged?

2024-02-20 19:59 UTC, tyner commented
Would be great to see it merged

2024-03-27 17:50 UTC, rokhmanov commented
Please!

2024-08-27 18:01 UTC, jrandall commented
@jon-mago would you be able to review and merge this, or would you be interested in considering new or additional maintainers for this repo (and possibly aws.signature as well)? If so, I might be interested. Though perhaps @condour or @laurenkahn can comment if they may be interested as well, since they have been the ones actively developing and reviewing the code in this PR.

2024-08-27 18:27 UTC, laurenkahn commented
I hope we can get this merged as well! Sadly I don't have permissions to merge. I tried to reach out to Jonathan Stott (the current maintainer of the package) via email in March 2024 and the email bounced. I'm not sure how else to get in touch.

2025-01-09 17:53 UTC, jb2cool commented
Whilst we are waiting for this to be merged (I too have reached out the the CloudyR community to try and get this merged in without success) I think this should work as a workaround. This installs the package directly from this pull request. Largely writing this so i can point people other people to this in the future

```
install.packages("devtools")
library(devtools)
devtools::install_github("cloudyr/aws.ec2metadata", ref = github_pull("11"))
```

That seems to work but is there an easier way to do this?

2025-12-07 16:37 UTC, jon-mago approved these changes

2025-12-07 16:38 UTC, merged